/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.11.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// SignedAggregateAndProof struct for SignedAggregateAndProof
type SignedAggregateAndProof struct {
	Message map[string]interface{} `json:"message,omitempty"`
	Signature string `json:"signature,omitempty"`
}
