/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.12.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// InlineObject3 The [`ProposerSlashing`](https://github.com/ethereum/eth2.0-specs/blob/v0.12.2/specs/phase0/beacon-chain.md#proposerslashing) object from the Eth2.0 spec.
type InlineObject3 struct {
	SignedHeader1 GetBlockHeadersResponseHeader `json:"signed_header_1,omitempty"`
	SignedHeader2 GetBlockHeadersResponseHeader `json:"signed_header_2,omitempty"`
}
