/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.12.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// GetProposerDutiesResponseData struct for GetProposerDutiesResponseData
type GetProposerDutiesResponseData struct {
	// The validator's BLS public key, uniquely identifying them. _48-bytes, hex encoded with 0x prefix, case insensitive._
	Pubkey string `json:"pubkey,omitempty"`
	Slot string `json:"slot,omitempty"`
}
