/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.11.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// InlineResponse2006Data Group of validators assigned to attest at specific slot and that have the same committee index (shard in phase 1)
type InlineResponse2006Data struct {
	Index string `json:"index,omitempty"`
	Slot string `json:"slot,omitempty"`
	// List of validator indices assigned to this committee
	Validators []string `json:"validators,omitempty"`
}
