/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.11.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// BeaconBlockAllOf1BodyEth1Data The [`Eth1Data`](https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/specs/phase0/beacon-chain.md#eth1data) object from the Eth2.0 spec.
type BeaconBlockAllOf1BodyEth1Data struct {
	DepositRoot string `json:"deposit_root,omitempty"`
	DepositCount string `json:"deposit_count,omitempty"`
	BlockHash string `json:"block_hash,omitempty"`
}
