/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.12.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// GetNetworkIdentityResponseData struct for GetNetworkIdentityResponseData
type GetNetworkIdentityResponseData struct {
	// Cryptographic hash of a peer’s public key. [Read more](https://docs.libp2p.io/concepts/peer-id/)
	PeerId string `json:"peer_id,omitempty"`
	// Ethereum node record. [Read more](https://eips.ethereum.org/EIPS/eip-778)
	Enr string `json:"enr,omitempty"`
	P2pAddresses []string `json:"p2p_addresses,omitempty"`
	DiscoveryAddresses []string `json:"discovery_addresses,omitempty"`
	Metadata GetNetworkIdentityResponseDataMetadata `json:"metadata,omitempty"`
}
