/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.12.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// AttesterDuty struct for AttesterDuty
type AttesterDuty struct {
	// The validator's BLS public key, uniquely identifying them. _48-bytes, hex encoded with 0x prefix, case insensitive._
	Pubkey string `json:"pubkey,omitempty"`
	CommitteeIndex string `json:"committee_index,omitempty"`
	CommitteeLength string `json:"committee_length,omitempty"`
	ValidatorCommitteeIndex string `json:"validator_committee_index,omitempty"`
	Slot string `json:"slot,omitempty"`
}
