/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.11.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// InlineResponse20021 struct for InlineResponse20021
type InlineResponse20021 struct {
	// Key value mapping of Phase 0[spec variables](https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/configs/mainnet.yaml). Values are returned with following format:   - any value starting with 0x in the spec is returned as a hex string   - all other values are returned as number 
	Data map[string]interface{} `json:"data,omitempty"`
}
