/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.12.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// BeaconState The [`BeaconState`](https://github.com/ethereum/eth2.0-specs/blob/v0.12.2/specs/phase0/beacon-chain.md#beaconblock) object from the Eth2.0 spec.
type BeaconState struct {
	GenesisTime string `json:"genesis_time,omitempty"`
	GenesisValidatorsRoot string `json:"genesis_validators_root,omitempty"`
	Slot string `json:"slot,omitempty"`
	Fork GetStateForkResponseData `json:"fork,omitempty"`
	// The [`BeaconBlockHeader`](https://github.com/ethereum/eth2.0-specs/blob/v0.12.2/specs/phase0/beacon-chain.md#beaconblockheader) object from the Eth2.0 spec.
	LatestBlockHeader map[string]interface{} `json:"latest_block_header,omitempty"`
	BlockRoots []string `json:"block_roots,omitempty"`
	StateRoots []string `json:"state_roots,omitempty"`
	HistoricalRoots []string `json:"historical_roots,omitempty"`
	Eth1Data BeaconStateEth1Data `json:"eth1_data,omitempty"`
	Eth1DataVotes []map[string]interface{} `json:"eth1_data_votes,omitempty"`
	Eth1DepositIndex string `json:"eth1_deposit_index,omitempty"`
	Validators []map[string]interface{} `json:"validators,omitempty"`
	// Validator balances in gwei
	Balances []string `json:"balances,omitempty"`
	RandaoMixes []string `json:"randao_mixes,omitempty"`
	// Per-epoch sums of slashed effective balances
	Slashings []string `json:"slashings,omitempty"`
	PreviousEpochAttestations []map[string]interface{} `json:"previous_epoch_attestations,omitempty"`
	CurrentEpochAttestations []map[string]interface{} `json:"current_epoch_attestations,omitempty"`
	// Bit set for every recent justified epoch
	JustificationBits string `json:"justification_bits,omitempty"`
	PreviousJustifiedCheckpoint GetStateFinalityCheckpointsResponseDataPreviousJustified `json:"previous_justified_checkpoint,omitempty"`
	CurrentJustifiedCheckpoint GetStateFinalityCheckpointsResponseDataPreviousJustified `json:"current_justified_checkpoint,omitempty"`
	FinalizedCheckpoint GetStateFinalityCheckpointsResponseDataPreviousJustified `json:"finalized_checkpoint,omitempty"`
}
