/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.12.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// BeaconBlockAllOf1BodyDeposits The [`Deposit`](https://github.com/ethereum/eth2.0-specs/blob/v0.12.2/specs/phase0/beacon-chain.md#deposit) object from the Eth2.0 spec.
type BeaconBlockAllOf1BodyDeposits struct {
	// Branch in the deposit tree.
	Proof []string `json:"proof,omitempty"`
	Data BeaconBlockAllOf1BodyData `json:"data,omitempty"`
}
