/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.11.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// InlineResponse20019Data struct for InlineResponse20019Data
type InlineResponse20019Data struct {
	HeadSlot interface{} `json:"head_slot,omitempty"`
	SyncDistance interface{} `json:"sync_distance,omitempty"`
}
