/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.11.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// InlineResponse200Data struct for InlineResponse200Data
type InlineResponse200Data struct {
	GenesisTime string `json:"genesis_time,omitempty"`
	GenesisValidatorsRoot string `json:"genesis_validators_root,omitempty"`
	// a fork version number
	GenesisForkVersion string `json:"genesis_fork_version,omitempty"`
}
