/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.11.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// ProposerSlashing The [`ProposerSlashing`](https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/specs/phase0/beacon-chain.md#proposerslashing) object from the Eth2.0 spec.
type ProposerSlashing struct {
	SignedHeader1 InlineResponse2007Header `json:"signed_header_1,omitempty"`
	SignedHeader2 InlineResponse2007Header `json:"signed_header_2,omitempty"`
}
