/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.11.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// InlineResponse2004Validator struct for InlineResponse2004Validator
type InlineResponse2004Validator struct {
	// The validator's BLS public key, uniquely identifying them. _48-bytes, hex encoded with 0x prefix, case insensitive._
	Pubkey string `json:"pubkey,omitempty"`
	WithdrawalCredentials string `json:"withdrawal_credentials,omitempty"`
	EffectiveBalance string `json:"effective_balance,omitempty"`
	// Was validator slashed (not longer active).
	Slashed bool `json:"slashed,omitempty"`
	ActivationEligibilityEpoch string `json:"activation_eligibility_epoch,omitempty"`
	ActivationEpoch string `json:"activation_epoch,omitempty"`
	ExitEpoch string `json:"exit_epoch,omitempty"`
	WithdrawableEpoch string `json:"withdrawable_epoch,omitempty"`
}
