/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.11.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// BeaconBlockAllOf1Body The [`BeaconBlockBody`](https://github.com/ethereum/eth2.0-specs/blob/v0.11.1/specs/phase0/beacon-chain.md#beaconblockbody) object from the Eth2.0 spec.
type BeaconBlockAllOf1Body struct {
	RandaoReveal string `json:"randao_reveal,omitempty"`
	Eth1Data BeaconBlockAllOf1BodyEth1Data `json:"eth1_data,omitempty"`
	Graffiti string `json:"graffiti,omitempty"`
	ProposerSlashings []InlineResponse20013Data `json:"proposer_slashings,omitempty"`
	AttesterSlashings []InlineResponse20012Data `json:"attester_slashings,omitempty"`
	Attestations []InlineResponse20011Data1 `json:"attestations,omitempty"`
	Deposits []BeaconBlockAllOf1BodyDeposits `json:"deposits,omitempty"`
	VoluntaryExits []InlineResponse20014Message `json:"voluntary_exits,omitempty"`
}
