/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.11.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// InlineResponse2007Data struct for InlineResponse2007Data
type InlineResponse2007Data struct {
	Root string `json:"root,omitempty"`
	Canonical bool `json:"canonical,omitempty"`
	Header InlineResponse2007Header `json:"header,omitempty"`
}
