/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.11.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// BeaconBlockAllOf struct for BeaconBlockAllOf
type BeaconBlockAllOf struct {
	Slot string `json:"slot,omitempty"`
	ProposerIndex string `json:"proposer_index,omitempty"`
	ParentRoot string `json:"parent_root,omitempty"`
	StateRoot string `json:"state_root,omitempty"`
}
