/*
 * Eth2 Beacon Node API
 *
 * API specification for the beacon node, which enables users to query and participate in Ethereum 2.0 phase 0 beacon chain.
 *
 * API version: Dev - Eth2Spec v0.12.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package eth2spec
// BeaconBlockAllOf1BodyData The [`DepositData`](https://github.com/ethereum/eth2.0-specs/blob/v0.12.2/specs/phase0/beacon-chain.md#depositdata) object from the Eth2.0 spec.
type BeaconBlockAllOf1BodyData struct {
	// The validator's BLS public key, uniquely identifying them. _48-bytes, hex encoded with 0x prefix, case insensitive._
	Pubkey string `json:"pubkey,omitempty"`
	WithdrawalCredentials string `json:"withdrawal_credentials,omitempty"`
	Amount string `json:"amount,omitempty"`
	Signature string `json:"signature,omitempty"`
}
